#!/usr/bin/env bash

# Generated by ./store.sh. Edit the parent .git/info/exclude and rerun store.sh.
declare -Ag DTVM_EXCLUDE_MAP=(
    [\*.dump]=managed
    [\*.jitted]=managed
    [\*.log]=managed
    [\*.so]=managed
    [.claude]=managed
    [AGENTS.md]=managed
    [ALL_STATE_TESTS]=managed
    [BRANCH_REPORT.md]=managed
    [CLAUDE.md]=managed
    [DTVMDotfiles]=managed
    [GEMINI.md]=managed
    [docs/research]=managed
    [erc20.evm.hex]=managed
    [fib.evm.hex]=managed
    [fibr.evm.hex]=managed
    [fixtures]=managed
    [init.sh]=managed
    [openspec]=managed
    [out.perf]=managed
    [perf]=managed
    [perf.data]=managed
    [perf.data.old]=managed
    [perf.data.old.\*]=managed
    [qa.md]=managed
    [static]=managed
    [tmp.sh]=managed
)
