#!/usr/bin/env bash

# Generated by ./store.sh. Edit the parent .git/info/exclude and rerun store.sh.
declare -Ag DTVM_EXCLUDE_MAP=(
    [\*\*/.claude/agent-memory-local]=managed
    [\*\*/.claude/agent-registry.json]=managed
    [\*\*/.claude/assistant-daemon-state.json]=managed
    [\*\*/.claude/checkpoints/]=managed
    [\*\*/.claude/first-run]=managed
    [\*\*/.claude/mailbox/]=managed
    [\*\*/.claude/routines/.state/]=managed
    [\*\*/.claude/scheduled_tasks.json]=managed
    [\*\*/.claude/scheduled_tasks.lock]=managed
    [\*\*/.claude/worktrees/]=managed
    [\*.dump]=managed
    [\*.jitted]=managed
    [\*.log]=managed
    [\*.so]=managed
    [.claude]=managed
    [.omx/]=managed
    [.pipeline/]=managed
    [.worktrees]=managed
    [AGENTS.md]=managed
    [ALL_STATE_TESTS]=managed
    [BRANCH_REPORT.md]=managed
    [CLAUDE.local.md]=managed
    [CLAUDE.md]=managed
    [DTVMDotfiles]=managed
    [GEMINI.md]=managed
    [docs/research]=managed
    [erc20.evm.hex]=managed
    [fib.evm.hex]=managed
    [fibr.evm.hex]=managed
    [fixtures]=managed
    [init.sh]=managed
    [out.perf]=managed
    [perf]=managed
    [perf.data]=managed
    [perf.data.old]=managed
    [perf.data.old.\*]=managed
    [qa.md]=managed
    [static]=managed
    [tmp.sh]=managed
    [tools/dtvm_local_test.sh]=managed
)
