#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/sync_common.sh
source "$SCRIPT_DIR/lib/sync_common.sh"

echo "Store script - Syncing files from $PARENT_DIR to $DOTFILES_DIR"
echo ""

storeMirroredItemsFromManifest "$PARENT_DIR" "$DOTFILES_DIR"

if [ -f "$PARENT_DIR/.git/info/exclude" ]; then
    declare -A ExcludeMap=()
    buildExcludeMapFromFile "$PARENT_DIR/.git/info/exclude" ExcludeMap
    writeMapFile \
        "$EXCLUDE_MAP_FILE" \
        "DTVM_EXCLUDE_MAP" \
        "# Generated by ./store.sh. Edit the parent .git/info/exclude and rerun store.sh." \
        ExcludeMap
    echo "  Stored: .git/info/exclude → $(basename "$EXCLUDE_MAP_FILE")"
else
    warn "Source not found: $PARENT_DIR/.git/info/exclude"
fi

echo ""
echo "✓ Store operation complete"
