#!/bin/bash
# SessionStart hook: read cached housekeeping report (generated by cron).
# Zero network calls, zero file hashing — just reads a text file.
#
# The heavy checks (gh API, diff.sh hash comparison) run weekly via cron:
#   crontab: 0 9 * * 1  bash ~/.claude/hooks/session-check-generate.sh
#
# This hook only displays the cached result if it exists and is < 7 days old.

set -euo pipefail

REPORT="$HOME/.claude/session-check-report.txt"

# No report file = nothing to show
[ -f "$REPORT" ] || exit 0

# Skip if report is older than 7 days (stale)
if [ "$(uname)" = "Darwin" ]; then
    AGE=$(( $(date +%s) - $(stat -f %m "$REPORT") ))
else
    AGE=$(( $(date +%s) - $(stat -c %Y "$REPORT") ))
fi
[ "$AGE" -gt 604800 ] && exit 0

# Read and display
CONTENT=$(cat "$REPORT")
[ -z "$CONTENT" ] && exit 0

JSON_CONTENT=$(echo "$CONTENT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
echo "{\"hookSpecificOutput\":{\"hookEventName\":\"SessionStart\",\"additionalContext\":\"$JSON_CONTENT\"}}"

exit 0
