#!/bin/bash
# SessionStart hook: read cached housekeeping report (generated by daily cron).
# Zero network calls, zero file hashing — just reads a text file.
#
# The heavy checks (gh API, diff.sh hash comparison) run daily via cron:
#   crontab: 0 9 * * *  bash ~/.claude/hooks/session-check-generate.sh
#
# This hook only displays the cached result if it exists and is < 1 day old.

set -euo pipefail

REPORT="$HOME/.claude/session-check-report.txt"

# No report file = nothing to show
[ -f "$REPORT" ] || exit 0

# Skip if report is older than 1 day (stale)
if [ "$(uname)" = "Darwin" ]; then
    AGE=$(( $(date +%s) - $(stat -f %m "$REPORT") ))
else
    AGE=$(( $(date +%s) - $(stat -c %Y "$REPORT") ))
fi
[ "$AGE" -gt 86400 ] && exit 0

# Read and display
CONTENT=$(cat "$REPORT")
[ -z "$CONTENT" ] && exit 0

JSON_CONTENT=$(echo "$CONTENT" | sed 's/\\/\\\\/g; s/"/\\"/g; :a; N; $!ba; s/\n/\\n/g')
echo "{\"hookSpecificOutput\":{\"hookEventName\":\"SessionStart\",\"additionalContext\":\"$JSON_CONTENT\"}}"

exit 0
